server:
  port: 8081

spring:
  application:
    name: ticket-management

  h2:
       console.enabled: true
  datasource:
    url: jdbc:h2:mem:dcbapp
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update
    show-sql: true

  main:
    allow-circular-references: true
  sql:
    init:
      mode: always

logging:
  level:
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE



